### ISSUE TITLE
Add Mac-specific menu-bar

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#117]
On Mac OS X the java-default menubar with application name "java" is shown. Add mac.specific code to beautify this (Application name SCADinspect)

**Comment by jonasber** [comment]
This is a bit complicated for newer macOS versions. I suggest a new issue regarding the whole bundling process for a macOS .app Application. More information: https://developer.apple.com/library/content/documentation/Java/Conceptual/Java14Development/03-JavaDeployment/JavaDeployment.html
