### ISSUE TITLE
Externalize all language strings into one properties-file

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#119]

**Comment by OrtiMussPrime** [comment]
My last commit is 888bb1472bff45c03c6b96a3d526ce71bb0bcbc8, changing assigned tasks with @Vaproc

**Comment by Vaproc** [comment]
@ibogicevic you wanted to solve the issue by your own and close it afterwards

**Comment by ibogicevic** [comment]
https://github.com/ibogicevic/SCADinspect/pull/262
