### ISSUE TITLE
Investigate on which parser to use

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#13]

**Comment by ibogicevic** [comment]
Include also the parser in the implementation (without sophisticated functionality).

**Comment by XOSplicer** [comment]
Also look into the language definition and implement the parsing

**Comment by XOSplicer** [comment]
| Name  | Type  | Details  | Pros  | Cons  |
|---|---|---|---|---|
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |

**Comment by ibogicevic** [comment]
I've got experience with xText but have never worked with the other parsers in the list. I would propose using CUP because of the background and the licence of the library.

**Comment by XOSplicer** [comment]
I am successfully working with jflex + cup at the moment.
Closing this issue now.
