### ISSUE TITLE
scadinspect.control.MyLogger.java

### ISSUE THREAD

**Issue by OrtiMussPrime** [ibogicevic/SCADinspect#133]
Based on Commit: 65964650b3c4cbe736d2fc2a72dae5296e2653a5

![image](https://cloud.githubusercontent.com/assets/20162797/24551998/0f543ab6-1625-11e7-8ea1-24881f53ba48.png)

**Comment by jokke150** [comment]
The branch review1-fix should be used for this.

https://github.com/ibogicevic/SCADinspect/tree/bugfix/review1-fix

**Comment by LisaMilius** [comment]
Pushed to branch feature/loggerFix and already merged
