### ISSUE TITLE
scadinspect.data.scaddoc.Module.java

### ISSUE THREAD

**Issue by OrtiMussPrime** [ibogicevic/SCADinspect#136]
Based on Merge: 65964650b3c4cbe736d2fc2a72dae5296e2653a5

![image](https://cloud.githubusercontent.com/assets/20162797/24552234/f5275cf8-1625-11e7-85b5-4d57e0f32fc1.png)

**Comment by Quintinius97** [comment]
Ein JavaDoc für eine equals Methode?? Die gehört zu jedem Objekt und wird hier nur überschrieben. Das ist so wie eine toString Methode zu dokumentieren

**Comment by OrtiMussPrime** [comment]
Dennoch war das Code Review Team der Meinung dass es ein JavaDoc haben sollte, vor allem weil es überschrieben wurde. @ivanbogicevic soll entscheiden

**Comment by jokke150** [comment]
If this will be implemented, the branch review1-fix should be used for this.

https://github.com/ibogicevic/SCADinspect/tree/bugfix/review1-fix

**Comment by ibogicevic** [comment]
Closing this as it it ok for this version. But it will reappear on the next codereview.
