### ISSUE TITLE
scadinspect.data.scaddoc.XmlExport.java

### ISSUE THREAD

**Issue by OrtiMussPrime** [ibogicevic/SCADinspect#137]
Based on Merge: 6596465

![image](https://cloud.githubusercontent.com/assets/20162797/24552274/18935e30-1626-11e7-84a5-a6d755337842.png)

**Comment by desyon** [comment]
Documentation already done in branch `feature/export`. The changes will be merged in the coming weeks. The issue will be closed automatically with the merge,
