### ISSUE TITLE
scadinspect.data.properties

### ISSUE THREAD

**Issue by OrtiMussPrime** [ibogicevic/SCADinspect#139]
Based on Merge: 6596465

![image](https://cloud.githubusercontent.com/assets/20162797/24552345/5b13e4a0-1626-11e7-8511-54d4fa70b65b.png)

**Comment by desyon** [comment]
@OrtiMussPrime `T` is the name of a generic. Generics can be used to use more than one Type in a class while maintaining that it is typesafe during runtime. More information about generics can be found [here](https://docs.oracle.com/javase/tutorial/java/generics/types.html

**Comment by desyon** [comment]
Getters are documented in the interface now. Further documentation is not necessary, as the implementations to not change the outcome of the method.

Changes are on the `feature\export` branch. It will be merged in the coming weeks. The issue will be closed automatically with the merge.

**Comment by OrtiMussPrime** [comment]
@desyon The question was what the three dots after the T mean. I think the most of us know that T is the name of a generic, since we had it in our Java lectures

**Comment by desyon** [comment]
The three dots stand for a variable number of arguments. In this specific case you can add any number of arguments to the constructor to create a list.
