### ISSUE TITLE
scadinspect.data.properties.helper.Pair.java

### ISSUE THREAD

**Issue by OrtiMussPrime** [ibogicevic/SCADinspect#140]
Based on Merge: 6596465

![image](https://cloud.githubusercontent.com/assets/20162797/24552376/764cba9e-1626-11e7-829e-9fb4b363b88f.png)

**Comment by desyon** [comment]
Getters are documented now. 

Changes are on the feature\export branch. It will be merged in the coming weeks. The issue will be closed automatically with the merge.
