### ISSUE TITLE
scadinspect.gui.AboutDialog.java

### ISSUE THREAD

**Issue by OrtiMussPrime** [ibogicevic/SCADinspect#142]
Based on Merge: 6596465

![image](https://cloud.githubusercontent.com/assets/20162797/24552425/a96621f4-1626-11e7-9184-cc66730b040c.png)

**Comment by ChimiDEV** [comment]
Is fixed in fdcaffe024e6862721bf9e54a6bad087a3836b19 (branch: bugfix/review1-fix)  
Pull request pending, when every other `Sprint Review 1` Issue is finished.
