### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#17]

**Comment by ChimiDEV** [comment]
`Another Logo Proposal:`  
![Another Logo](http://i.imgur.com/n9iE6Zq.png)

**Comment by Vaproc** [comment]
![scadinspect logo](https://cloud.githubusercontent.com/assets/20164916/26001918/38ef264a-372e-11e7-99f4-1bccbfa2056c.png)

**Comment by Vaproc** [comment]
the logo from @ChimiDEV won the voting and is therefore our logo
