### ISSUE TITLE
Add description / documentation about all checkers

### ISSUE THREAD

**Issue by jonasber** [ibogicevic/SCADinspect#181]
There is a dialog (CheckersDialog) which should show the user all the checkers SCADInspect is using to check sources. The Dialog is functioning but it lacks of content.

**Comment by ibogicevic** [comment]
@jonasber, could you please ask @XOSplicer what checkers (only the about 3 to 5 demo checkers) will be implemented and then formulate and add the documentation accordingly (one sentence for each checker is enough)
