### ISSUE TITLE
Plan GUI Test

### ISSUE THREAD

**Issue by romyroemke** [ibogicevic/SCADinspect#191]

**Comment by jokke150** [comment]
We want to use TestFX for the GUI tests.

Reference: https://github.com/TestFX/TestFX

**Comment by romyroemke** [comment]
•	Open file/folder
-	Open file/folder from file explorer
•	Settings
-	Autorefresh
-	Logging Level
•	Export
•	Refresh
•	Close file
•	Help
•	About
•	Issue list
•	Documentation list

**Comment by jokke150** [comment]
The branch "feature/testing" will be used for the GUI tests.
