### ISSUE TITLE
Sprint1-fix: Version Number

### ISSUE THREAD

**Issue by ChimiDEV** [ibogicevic/SCADinspect#217]
Find a way to show the version number in the about dialog.  
 _(Maven property META-INF)_

**Comment by ChimiDEV** [comment]
We don't want to hardcore the version number inside a string, so we tried to use properties and a `filter`  tag within the maven pom file (as the version is declared here), but @jokke150 and I did not get it to work until now.

**Comment by ibogicevic** [comment]
postponed
