### ISSUE TITLE
implement example checkers 

### ISSUE THREAD

**Issue by XOSplicer** [ibogicevic/SCADinspect#224]
implementation of #211

**Comment by XOSplicer** [comment]
implemented Special Variables Check (no non-special variable starting with $) in 49d1e3723c96995fd4e4f0a57a8bab8bca1923b8

**Comment by XOSplicer** [comment]
The other example checkers will be implemented later, so this issue is moved to Sprint 4

**Comment by ibogicevic** [comment]
Static-feature of SCADinspect is postponed.
