### ISSUE TITLE
Opening/Closing files

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#31]
Extend the current implementation so that a .scad-file can be opened and closed.
Two persons should work on this.

**Comment by ibogicevic** [comment]
It should also be possible to open/close folders.
The current open file/folder should be states in the titlebar (after "SCADinspect –")

**Comment by OrtiMussPrime** [comment]
Fixed the existing path problem with commit 9e2167f00ccf896fe7cee1cbc70b425377660966 and 322ddb3b2218db2050c49d1ce12d401d7b31710d.

New problem is that JavaFX only can have a directory chooser OR a file chooser.
Even in the file chooser we have to distinguish between ONE or MULTIPLE selectable files.

**Comment by OrtiMussPrime** [comment]
After speaking with @ibogicevic  and @jonasber we decided to do two open dialogs.
One is: "Open File" and the other one is "Open Folder".

Issue opened: #64

**Comment by OrtiMussPrime** [comment]
New Issue discovered:
Directories were opened when selected "open files" but the files were not loaded.
Now the ProjectHandler opens also the files and adds them into a file list.
I added a getFileList function so others can use the file list.
Also updated the close function of the ProjectHandler.
See commit: af14c1dab4a422978252344f7f951164c12f0a67

**Comment by OrtiMussPrime** [comment]
Next on the ToDo-List:
Check if "Open folder" includes subfolders as well.

**Comment by OrtiMussPrime** [comment]
"Open folders" does not include subfolders.
This has to be implemented.

**Comment by OrtiMussPrime** [comment]
Implemented search of subfolders.
Reformatted code according to the google styleguide.
