### ISSUE TITLE
Review of GUI-Prototype

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#32]
Technical review of the GUI-Prototype: https://github.com/ibogicevic/SCADinspect/blob/master/spec/proto/sketch.ep

Four persons should work on this: one moderator (who also protocols) and two examiners
Include also missing items and additional new ideas for the gui.

**Comment by OrtiMussPrime** [comment]
@jonasber Please keep me updated if the close button will be removed from the toolbar.

**Comment by ibogicevic** [comment]
Reduced this review to a walkthrough (see #59) as we will make a large review at the end of sprint 1.
