### ISSUE TITLE
Implement help-dialog

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#34]
When the user clicks on "help" a large (website-like) dialog should be shown.

**Comment by ibogicevic** [comment]
...add some dummy chapters with dummy content. Real content should be added with #54

**Comment by maikbaumgartner** [comment]
@ibogicevic  Besides the help modal, which gives a short tour through the program, should the documentation link to a html file or to a javafx dialog?

**Comment by ibogicevic** [comment]
The documentation should completely be inside the help dialog. A navigation at the left side of the window would be nice. The rest can look like the content of a website (or just simple text with links).

**Comment by ibogicevic** [comment]
Closing this issue as the help dialog is included with 46c3ce8ade1ba7651698ba1294d5d8f29833f4bb.
For additions to the dialog, please open new issues associated to sprint 2
