### ISSUE TITLE
Implement the "refresh" button w/ message and a progress bar

### ISSUE THREAD

**Issue by DavidBMaier** [ibogicevic/SCADinspect#41]
Set up the general structure for refreshing with classes and minimal functionality.

**Comment by LisaMilius** [comment]
Also working on this issue

**Comment by LisaMilius** [comment]
Progress-Text and ProgressBar are set visible when clicking "refresh" and Thread is invoked to simulate progress, updating the ProgressBar in predefined Intervals.
