### ISSUE TITLE
Find detailed language definition and implement parser

### ISSUE THREAD

**Issue by JoBa97** [ibogicevic/SCADinspect#42]

**Comment by XOSplicer** [comment]
Lexer can be found here: https://github.com/openscad/openscad/blob/master/src/lexer.l
Parser here: https://github.com/openscad/openscad/blob/master/src/parser.y

**Comment by XOSplicer** [comment]
Current Status: We still need to implement the generation of the Parse Tree

**Comment by XOSplicer** [comment]
Possible Enhancement: CUP offers the functionality of error recovery, such that more than one syntax errors may be found...

**Comment by XOSplicer** [comment]
Current TODOs: 
- handle include statements somehow
- clear Situation about Unicode
- handle escaped HEX numbers in strings
- build the parse tree ( #154 )

**Comment by XOSplicer** [comment]
closed as of #170
