### ISSUE TITLE
Create Conventions File

### ISSUE THREAD

**Issue by tilgoepfert** [ibogicevic/SCADinspect#44]
Create a file listing all conventions concerning code style, branching and more.

**Comment by niksauer** [comment]
Please adhere to the rules provided in the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html).

**Comment by tilgoepfert** [comment]
Conventions are available in `/spec`

**Comment by ibogicevic** [comment]
Ok!
Direct Link is: https://github.com/ibogicevic/SCADinspect/blob/master/spec/Conventions.md
