### ISSUE TITLE
Define data-model for docu

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#5]
and save as UML file under /spec/datamodel_doc

**Comment by ibogicevic** [comment]
#25 should be solved before this

**Comment by desyon** [comment]
I think we can mostly adapt the format of JavaDoc, in the following form:

```
@key value
@key multivalue1, multivalue2
@key multivalue1, multivalue2
```

but we need to consider some special cases like prices and weight that need to be handeled differntly in internal processing

**Comment by ibogicevic** [comment]
To avoid redudancy we only document the format inside the help-dialog. See #192
