### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by JoBa97** [ibogicevic/SCADinspect#50]
Please set the master branch to protected and make sure a pull request has to be reviewed before merging it into master. If you require an administrator to review the pull request, I need to be added to the administrator group of this repository.

**Comment by ibogicevic** [comment]
Ok, I agree on that. I protected the master branch. Administrator rights for reviews are currently not needed, but if you need them for other purposes (extended GitHub-Settings), please inform me so I can add you to the list of admins, that's no problem.
