### ISSUE TITLE
Activate and configure TravisCI

### ISSUE THREAD

**Issue by desyon** [ibogicevic/SCADinspect#51]
Please activate the TravisCI connection to simplify the pull request process.

**Comment by XOSplicer** [comment]
The owner  of the respository, @ibogicevic , need to activate this in Travis (https://travis-ci.org/).
But I heard @JoBa97 will be admin user soon, so maybe he can also activate this repo in his account, but that is only a guess. I can still however provide a .travis.yml build script.

**Comment by XOSplicer** [comment]
@ibogicevic, To activate TravisCI for this repo please go to https://travis-ci.org/ , sign in with github, accept all the license and access permission promts and finally flip the switch for this repo to enable it.

**Comment by XOSplicer** [comment]
So I think TravisCi is activated now (https://travis-ci.org/ibogicevic/SCADinspect/builds)
We can show of the build status in the README.md using the build status image.

**Comment by ibogicevic** [comment]
I agree on using TravisCI as it is the best solution in combination with GitHub (although I worked much more with Jenkins up to now).
