### ISSUE TITLE
Adjust user interface

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#59]
...according to https://github.com/ibogicevic/SCADinspect/blob/master/spec/proto/sketch_proposal.ep

and:

1. We need the close-Button back (right next to the open-button) because although technically it is not needed, it is a common important usability guideline to provide the users the possibility to get the status his application was before his last action. Without the close-Button this wouldn't be possible.

2. I would like the text about SCADinspect to be moved to inside the help-dialog.

**Comment by jonasber** [comment]
@ibogicevic Is it ok, if the close button is at the bottom right, like in commit 3f18f22 ? It looks better and makes sense in terms of interaction flow.

**Comment by ibogicevic** [comment]
Yes, the button position is ok (at least for now).

**Comment by ibogicevic** [comment]
Closing issue as functionality has been added with 77838d6
