### ISSUE TITLE
Where Can static Analysis issues bei Reported ?

### ISSUE THREAD

**Issue by XOSplicer** [ibogicevic/SCADinspect#73]
Ist there already a Central place in the program where issues Can be reported ? When the Parser finds an Syntax error or an illigal character this should Show up in the issue list? Ist there already a mechanism in place ?

**Comment by XOSplicer** [comment]
@ChimiDEV I saw you are authoring the Issue class, maybe you know something ?

**Comment by ChimiDEV** [comment]
@XOSplicer At the moment the `Issues Class` includes only the informations that an issue has (like lineNumber), you could use the constructor for constructing the issue.
As far as I konw, Tom and Phil are working on a implemetation of an issue list, which collects all of the issues that are instantiated.
I think the `Issue Class` is the answer for this, we can talk about that later.

**Comment by ibogicevic** [comment]
Can this issue be closed or are there still open questions?

**Comment by ChimiDEV** [comment]
@ibogicevic We resolved that question, issue can be closed.
