### ISSUE TITLE
Implement HTML Export of docu data

### ISSUE THREAD

**Issue by ibogicevic** [ibogicevic/SCADinspect#9]

**Comment by desyon** [comment]
The class is now implemented and only small tweaks have to be done. As the HTML Table is supposed to be exported to PDF format as well the table should be formatted to a certain degree. 

The formatting itself will be only a ``style`` block in the html document, but the question arising is if there is some color scheme defined somewhere that can be used in this styling?

**Comment by EricFelix** [comment]
Checked whether HtmlExporter has same issue with some characters -> not true
Works as expected.
